---
title: "analysis"
author: "Yixuan Yang"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```


```{r}
# load preprocessed data
st <- readRDS('st.rds')
tax <- readRDS('tax.rds')
taxsp <- readRDS('taxsp.rds')
ft <- sweep(st, 1, rowSums(st), "/")
meta_data <- read_xlsx('epilepsy_mapping.xlsx') %>% arrange(str_rank(SampleID, numeric = T))
meta_data <- meta_data[1:118,]
meta_data$SampleID[1] <- meta_data$SampleID[1] %>% str_c('8') # Netti_J8 is missing in meta data file. should double check later
meta_data <- meta_data %>% arrange(str_rank(SampleID, numeric = T)) %>% data.frame(stringsAsFactors = T)
```

Here we can first look at helicobactor.

```{r}
helico.sq <- getSequences(tax)[which(tax[,6] %in% 'Helicobacter')]
taxsp[helico.sq,7] %>% unname
```

Not all sequences are assigned to a species. Here we need to use web BLAST

```{r}
dada2:::pfasta(helico.sq)
```
```{r}
helico.species <- c('canis',
                    'canis',
                    'canis',
                    'canicola/cinaedi/bills',
                    'canicola/cinaedi/bills',
                    'canis',
                    'canis', # 99.6
                    'bills',
                    'canicola/cinaedi/bills',
                    'canis', # 99.6
                    'canicola/cinaedi',
                    'winghamensis',
                    'canis') # 95.56

canis.sq <- helico.sq[helico.species =='canis']
```

```{r}
canis.prop <- ft[,canis.sq]
colnames(canis.prop) <- str_c('helico.canis',1:7)
cor(canis.prop)
outer(canis.sq, canis.sq, nwhamming, vec = T)
```

```{r}
meta_data <- meta_data %>% cbind(canis.prop = rowSums(canis.prop))
```

```{r}
meta_data <- meta_data %>% arrange(str_rank(Household, numeric = TRUE))
meta_data$Group <- factor(meta_data$Group)
t.test(canis.prop~Group, data = meta_data, paired = TRUE)
```

