---
title: "Pilot Study Callback"
author: "Yixuan Yang"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# SetUp

```{r message=FALSE}
set.seed(2024)
library(tidyverse)
library(here)
library(phyloseq)
theme_set(theme_bw())

ps <- readRDS(here('data','following_study','ps_rarefied.rds')) %>%
    filter_taxa(function(x) {
        prevlance <- sum(x > 0) / length(x)
        prevlance > 0.1
        }, prune = TRUE)
ps.genus <- readRDS(here('data','following_study','ps_rarefied.rds')) %>% 
    tax_glom('Genus') %>% 
    subset_taxa(Genus == 'Collinsella')
taxa_names(ps.genus) <- 'Genus'

# add genus level collinsella count to otu table
otu.df <- otu_table(ps.collinsella) %>% 
    cbind(Genus = otu_table(ps.genus)) %>%
    cbind(data.frame(sample_data(ps.collinsella))) %>% 
    pivot_longer(c(starts_with('ASV'), 'Genus'), names_to = 'ASV', values_to = 'Abundance')


lfc <- otu.df %>%
    group_by(Household, ASV) %>%
    summarise(LFC = log2(Abundance[Epileptic.or.Control == "Epileptic"] + 1) -
                  log2(Abundance[Epileptic.or.Control == "Control"] + 1),
              .groups = 'drop')
```