---
title: "Explore Collinsella"
output: html_document
date: "2024-07-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Set Up

```{r message=FALSE}
library(tidyverse)
library(here)
library(phyloseq)
theme_set(theme_bw())

filt_fun <- function (x, min_reads = 100, min_samples = 5) {
    (sum(x) > min_reads) & (sum(x > 0) > min_samples)
}

ps <- readRDS(here('data','following_study','ps.rds')) %>% 
    filter_taxa(filt_fun, prune = TRUE) 
ps

sam <- sample_data(ps) %>% data.frame()
otu <- otu_table(ps) %>% data.frame()
tax <- tax_table(ps) %>% data.frame() %>% rownames_to_column('taxon')

tax.collin <- tax %>% filter(Genus == 'Collinsella')
otu.clr <- (otu + 1) %>% 
    # vegan::decostand('clr', pseudocount = 0.5) %>% # prior value same as aldex2
    log2() %>% 
    dplyr::select(tax.collin$taxon) %>% 
    bind_cols(dplyr::select(sam, Epileptic.or.Control))


sam.long <- sam %>%
    bind_cols(otu.clr[,tax.collin$taxon]) %>% 
    pivot_longer(cols = starts_with('ASV'), names_to = 'ASV', values_to = 'abundance')

sam.long.exist <- data.frame(sam) %>%
    bind_cols(sign(otu[,tax.collin$taxon])) %>%
    pivot_longer(starts_with('ASV'), names_to = 'ASV', values_to = 'exist')
```

In the session of differential abundance analysis, we have found that `Collinsella` could be an influential ASV. Here we investigate its existence.

```{r}
otu.epi <- otu.clr %>%
    filter(Epileptic.or.Control == 'Epileptic') %>% 
    dplyr::select(-Epileptic.or.Control)
otu.ctl <- otu.clr %>% 
    filter(Epileptic.or.Control == 'Control') %>% 
    dplyr::select(-Epileptic.or.Control)

otu.diff <- data.frame(otu.epi - otu.ctl) %>%
    mutate(Household = unique(sam$Household)) %>% 
    pivot_longer(!Household, names_to = 'ASV', values_to = "LFC")

ggplot(otu.diff) +
    geom_bar(aes(x = as.numeric(Household), y = LFC, fill = ASV), stat = 'identity') +
    labs(x = 'Household', y = 'log 2 fold change')

ggplot(otu.diff) +
    geom_bar(aes(x = as.numeric(Household), y = LFC, fill = (LFC > 0)), stat = 'identity') +
    facet_wrap(~ASV, scales = 'free_y') +
    labs(x = 'Household', y = 'log 2 fold change', fill = 'LFC > 0')

ggplot(sam.long) +
    geom_violin(aes(x = Epileptic.or.Control, y = abundance)) +
    geom_jitter(aes(x = Epileptic.or.Control, y = abundance, colour = (abundance == 0)), width = 0.3) +
    labs(y = 'log 2 abundance', color='Structual Zero') +
    facet_wrap(~ASV, scales = 'free_y')
```

# Contingency Tables

## Epileptic or control

```{r}
options(dplyr.summarise.inform = FALSE)
sam.long.exist %>%
    group_by(Epileptic.or.Control, ASV, exist) %>%
    summarise(n=n()) %>%
    spread(Epileptic.or.Control, n) %>% gt::gt()
```

## Breed

```{r}
sam.long.exist %>%
    group_by(Breed.Group..1., ASV, exist) %>%
    summarise(n=n()) %>%
    spread(Breed.Group..1., n) %>% gt::gt()
```

## Drug Usage

```{r}
sam.long.exist %>%
    group_by(Pheno.Y.N, ASV, exist) %>%
    summarise(n=n()) %>%
    spread(Pheno.Y.N, n) %>% gt::gt()
```

## Sex

```{r}
sam.long.exist %>%
    group_by(Sex, ASV, exist) %>%
    summarise(n=n()) %>%
    spread(Sex, n) %>% gt::gt()
```
