---
title: "PERMANOVA test"
author: "Yixuan Yang"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(tidyverse)
library(phyloseq)
library(vegan)
library(phangorn)
library(DECIPHER)
library(here)
library(reshape2)
theme_set(theme_minimal())
```

```{r}
# OTU table is in proportion in this situation
ps <- readRDS(here('Rdata','following_study','ps.rds')) %>%
    transform_sample_counts(function(x) x / sum(x) )
fitGTR <- readRDS(here('Rdata','following_study','fitGTR.rds'))
psord <- merge_phyloseq(ps, phy_tree(fitGTR$tree))

```


```{r}
ord.bray.mds <- ordinate(psord, method="MDS", distance="bray")
ord.bray.nmds <- ordinate(psord, method="NMDS", distance="bray")
ord.wuf.mds <- ordinate(psord, method="MDS", distance="wunifrac")
ord.wuf.nmds <- ordinate(psord, method="NMDS", distance="wunifrac")
```

```{r}
plot.ord <- function(psi, ordi, color="Group", label="Household", size=3, axes=c(1,2)) {
  p <- plot_ordination(psi, ordi, axes=axes)
  ggplot(data=p$data, aes_string(x=quo_name(p$mapping$x), y=quo_name(p$mapping$y), 
                                 color=color, label=label)) + geom_text(size=size, check_overlap = T)
}

p.bray <- plot.ord(psord, ord.bray.mds)
p.bray + ggtitle("Bray - MDS")
plot.ord(psord, ord.bray.nmds) + ggtitle("Bray - NMDS")

p.wuf <- plot.ord(psord, ord.wuf.mds)
p.wuf + ggtitle("WUF - MDS")
plot.ord(psord, ord.wuf.nmds) + ggtitle("WUF - NMDS")
```

```{r include=FALSE}
ds <- phyloseq::distance(psord, 'unifrac') 
sam <- sample_data(psord) %>% data.frame()
sam.dic <- hash::hash(rownames(sam), sam$Household)
ds.m = as.matrix(ds) %>%
    melt() %>% 
    mutate(Var1 = str_remove(Var1,'Netti')) %>% 
    mutate(Var2 = str_remove(Var2,'Netti')) %>% 
    mutate_if(is.character,as.numeric)
ds.m
dog.dist <- c()
for (i in seq(1,106,by = 2)) {
    data <- filter(ds.m, Var2 == i & Var1 != i)
    avg <- mean(data$value)
    pair <- (filter(data, Var1 == i+1))$value
    dog.dist <- dog.dist %>% rbind(c(pair, avg))
}
```


permanova test for household

```{r}
bc <- phyloseq::distance(psord, method="bray")
samdf.ord <- data.frame(sample_data(psord))
vegan::adonis2(bc ~ Household, data = samdf.ord, permutations=1e4)
```

```{r}
vegan::adonis2(bc ~ Pheno.Y.N, data = samdf.ord, permutations=1e4)
```

```{r}
vegan::adonis2(bc ~ State.Infor, data = samdf.ord, permutations=1e4)
```

```{r}
psord.age <- psord %>% subset_samples(is.na(Age..months.) == F)
bc.age <- phyloseq::distance(psord.age, method="bray")
samdf.ord.age <- data.frame(sample_data(psord.age))
vegan::adonis2(bc.age ~ Age..months., data = samdf.ord.age, permutations=1e4)
```

# PCoA

```{r}
ps.uf <- UniFrac(psord)
pcoa <- ordinate(psord, method="PCoA", distance=ps.uf)
plot_scree(pcoa)
plot.ord(psord, pcoa)
```

