---
author: "Yixuan Yang"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE}
rm(list = ls())
library(phyloseq)
library(tidyverse)
library(here)
```

```{r}
path <- here('Rdata','following_study')
meta_data <- readRDS(here(path,'metadata.rds'))
st <- readRDS(here(path, 'st_new.rds'))
taxa <- readRDS(here(path,'taxsp.rds'))

str(meta_data)
# keep the matched sample ID
rownames(meta_data) <- 'Netti' %>% str_c(sprintf("%03d", as.integer(meta_data$SampleID2)))
# meta_data <- meta_data[,3:12]

if(!identical(nrow(meta_data), nrow(st))) stop('meta data does not match with sequence table')
if(!identical(rownames(meta_data), rownames(st))) stop('rownames in meta data does not match with sequence table')
```

```{r}
# Get phyloseq components
OTU <- otu_table(st, taxa_are_rows = F)
SAM <- sample_data(meta_data %>% bind_cols(study = 'following'))
TAX <- tax_table(taxa)
# Combine into a phyloseq object
ps <- phyloseq(OTU, SAM, TAX)
# Add ASV sequences
seqs <- Biostrings::DNAStringSet(taxa_names(ps))
names(seqs) <- taxa_names(ps)
ps <- merge_phyloseq(ps, seqs)
ps
taxa_names(ps) <- paste0("ASV", seq(ntaxa(ps))) # here we store 
```

```{r}
saveRDS(ps, here(path,'ps.rds'))
```

Here we also organize pilot study data into phyloseq

```{r}
path <- here('Rdata','pilot_study')
meta_data <- readRDS(here(path,'metadata.rds'))
st <- readRDS(here(path, 'st.rds'))
taxa <- readRDS(here(path,'taxp.rds'))
```

```{r}
rownames(st) <- rownames(st) %>% str_remove('_F.fastq')
# Get phyloseq components
OTU <- otu_table(st, taxa_are_rows = F)
SAM <- sample_data(meta_data %>% bind_cols(study = 'pilot'))
TAX <- tax_table(taxa)
# Combine into a phyloseq object
ps.pilot <- phyloseq(OTU, SAM, TAX)
# Add ASV sequences
seqs <- Biostrings::DNAStringSet(taxa_names(ps.pilot))
names(seqs) <- taxa_names(ps.pilot)
ps.pilot <- merge_phyloseq(ps.pilot, seqs)
ps.pilot
taxa_names(ps.pilot) <- paste0("ASV", seq(ntaxa(ps.pilot))) # here we store 
saveRDS(ps.pilot, here(path,'ps.rds'))
```


```{r}
ps.all <- merge_phyloseq(ps.pilot, ps)
ps.all
saveRDS(ps.all, here('Rdata','ps_all.rds'))
```

