---
title: "Pilot Study"
author: "Yixuan Yang"
output:
  html_document:
    toc: true
    toc_float: true
    self_contained: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Set Up

```{r message=FALSE}
set.seed(2024)
library(tidyverse)
library(here)
library(phyloseq)
library(dada2)
library(DECIPHER)
```

# Read in metadata

```{r}
metadata <- read.csv(here('data','pilot_study','epilepsy_metadata.tsv'), sep = '\t') %>% 
    add_column(study = 'pilot')
rownames(metadata) <- metadata$SampleID
head(metadata)
```

# Read in sequence table

```{r}
st <- readRDS(here('data','pilot_study','st.rds'))
rownames(st) <- rownames(st) %>% str_remove('_F.fastq.gz')
if (!identical(rownames(metadata), rownames(st))) {stop('Sample names do not match')}
```

# Assign taxonomy using Silva 138.1

```{r eval=FALSE}
tax <- assignTaxonomy(st, "~/tax/silva_nr99_v138.1_train_set.fa.gz", multithread=TRUE)
taxsp <- addSpecies(tax, "~/tax/silva_species_assignment_v138.1.fa.gz")
saveRDS(tax, here("data", "pilot_study", "tax.rds"))
saveRDS(taxsp, here("data", "pilot_study", "taxsp.rds"))
```

# Save everything to phyloseq object

```{r}
taxsp <- readRDS(here("data", "pilot_study", "taxsp.rds"))
ps <- phyloseq(sample_data(metadata),
               otu_table(st, taxa_are_rows = FALSE), 
               tax_table(taxsp))
# Add ASV sequences
seqs <- Biostrings::DNAStringSet(taxa_names(ps))
names(seqs) <- taxa_names(ps)
ps <- merge_phyloseq(ps, seqs)
taxa_names(ps) <- paste0("ASV", seq(ntaxa(ps))) 
```

# Save the phyloseq object

```{r}
ps

saveRDS(ps, file = here('data','pilot_study','ps.rds'))
```


